version: '3'
services:
  proxy:
    image: proxy
    volumes:
      - "./proxy/index.js:/apps/http-proxy-middleware/examples/connect/index.js"
    ports:
      - 2000:2000
  freecoin-api:
    image: vmatekole/freecoin-api
    command: "/app/bin/lein ring server-headless"
    volumes:
      - "./project.clj:/app/src/project.clj"
      - "./freecoin/config:/app/src/resources"
      - "./faircoin2-testnet/config:/faircoin2/config"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  faircoin-testnet:
    image: local-faircoin
    volumes:
      - /mnt/data/faircoin2-testnet:/faircoin2
      - $PWD/faircoin2-testnet/config/faircoin.conf:/faircoin2/config/faircoin.conf
    command: -datadir=/faircoin2/data -conf=/faircoin2/config/faircoin.conf -debug -testnet -printtoconsole
    ports:
      - 41404:41404
      - 41405:41405
  faircoin:
    image: local-faircoin
    volumes:
      - /mnt/data/faircoin2:/faircoin2
      - $PWD/faircoin2/config/faircoin.conf:/faircoin2/config/faircoin.conf
    command: -datadir=/faircoin2/data -conf=/faircoin2/config/faircoin.conf -debug  -printtoconsole
    ports:
      - 40404:40404
      - 40405:40405
